const crypto = require('crypto')

function generateSecret(length = 64) {
  return crypto.randomBytes(length).toString('hex').slice(0, length)
}

module.exports = {
  run: [
    // Clone postiz-docker-compose repo
    {
      when: "{{!exists('app')}}",
      method: "shell.run",
      params: {
        message: [
          "git clone https://github.com/gitroomhq/postiz-docker-compose.git app"
        ]
      }
    },
    // Generate .env from template
    {
      when: "{{!exists('app/.env')}}",
      method: "shell.run",
      params: {
        path: "app",
        message: [
          "cp ../.env.example .env || true"
        ]
      }
    },
    // Generate JWT secret
    {
      when: "{{!exists('app/.env')}}",
      method: "fs.write",
      params: {
        path: "app/.env",
        content: `# Auto-generated by Pinokio launcher
# Edit this file to configure social media integrations

MAIN_URL=http://localhost:4007
FRONTEND_URL=http://localhost:4007
NEXT_PUBLIC_BACKEND_URL=http://localhost:4007/api
JWT_SECRET=${generateSecret(64)}
DATABASE_URL=postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local
REDIS_URL=redis://postiz-redis:6379
BACKEND_INTERNAL_URL=http://localhost:3000
TEMPORAL_ADDRESS=temporal:7233
IS_GENERAL=true
DISABLE_REGISTRATION=false
RUN_CRON=true
STORAGE_PROVIDER=local
UPLOAD_DIRECTORY=/uploads
NEXT_PUBLIC_UPLOAD_DIRECTORY=/uploads

# === Social Media API Keys (edit to enable platforms) ===
X_API_KEY=
X_API_SECRET=
LINKEDIN_CLIENT_ID=
LINKEDIN_CLIENT_SECRET=
REDDIT_CLIENT_ID=
REDDIT_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
THREADS_APP_ID=
THREADS_APP_SECRET=
FACEBOOK_APP_ID=
FACEBOOK_APP_SECRET=
YOUTUBE_CLIENT_ID=
YOUTUBE_CLIENT_SECRET=
TIKTOK_CLIENT_ID=
TIKTOK_CLIENT_SECRET=
PINTEREST_CLIENT_ID=
PINTEREST_CLIENT_SECRET=
DRIBBBLE_CLIENT_ID=
DRIBBBLE_CLIENT_SECRET=
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
DISCORD_BOT_TOKEN_ID=
SLACK_ID=
SLACK_SECRET=
SLACK_SIGNING_SECRET=
MASTODON_URL=https://mastodon.social
MASTODON_CLIENT_ID=
MASTODON_CLIENT_SECRET=
BEEHIIVE_API_KEY=
BEEHIIVE_PUBLICATION_ID=

# === AI ===
OPENAI_API_KEY=

# === Misc ===
EXTENSION_ID=icpokdlcikdmemjkeoojhocmhmehpaia
API_LIMIT=30
FEE_AMOUNT=0.05
NX_ADD_PLUGINS=false
`
      }
    },
    // Pull docker images
    {
      method: "shell.run",
      params: {
        path: "app",
        message: [
          "docker compose pull"
        ]
      }
    }
  ]
}
