const crypto = require('crypto')

// Generate JWT secret at module load time
const JWT_SECRET = crypto.randomBytes(64).toString('hex').slice(0, 64)

module.exports = {
  run: [
    // Check if Docker is installed
    {
      method: "shell.run",
      params: {
        message: [
          "echo '═══════════════════════════════════════════'",
          "echo '  Postiz Installer - Checking Dependencies'",
          "echo '═══════════════════════════════════════════'",
          "echo ''",
          "if command -v docker &> /dev/null; then",
          "  echo '✓ Docker is installed'",
          "  docker --version",
          "else",
          "  echo '✗ Docker not found'",
          "  echo ''",
          "  touch /tmp/postiz_need_docker",
          "fi"
        ]
      }
    },
    // Install Docker if needed
    {
      when: "{{exists('/tmp/postiz_need_docker')}}",
      method: "shell.run",
      params: {
        message: [
          "echo ''",
          "echo 'Installing Docker...'",
          "echo ''",
          "curl -fsSL https://get.docker.com | sudo sh",
          "sudo usermod -aG docker $USER",
          "echo ''",
          "echo '═══════════════════════════════════════════'",
          "echo '  Docker installed successfully!'",
          "echo '═══════════════════════════════════════════'",
          "echo ''",
          "touch /tmp/postiz_need_restart",
          "rm -f /tmp/postiz_need_docker"
        ]
      }
    },
    // Prompt for restart if Docker was just installed
    {
      when: "{{exists('/tmp/postiz_need_restart')}}",
      method: "shell.run",
      params: {
        message: [
          "rm -f /tmp/postiz_need_restart",
          "echo ''",
          "echo '╔═══════════════════════════════════════════╗'",
          "echo '║         ⚠️  ACTION REQUIRED               ║'",
          "echo '╚═══════════════════════════════════════════╝'",
          "echo ''",
          "echo 'Docker has been installed and your user has'",
          "echo 'been added to the docker group.'",
          "echo ''",
          "echo 'Please do ONE of the following:'",
          "echo ''",
          "echo '  Option 1: Open a terminal and run:'",
          "echo '            newgrp docker'",
          "echo '            Then click Install again'",
          "echo ''",
          "echo '  Option 2: Log out and log back in'",
          "echo '            Then click Install again'",
          "echo ''",
          "echo '  Option 3: Restart Pinokio'",
          "echo '            Then click Install again'",
          "echo ''",
          "echo '═══════════════════════════════════════════'",
          "exit 0"
        ]
      }
    },
    // Verify Docker is accessible
    {
      method: "shell.run",
      params: {
        message: [
          "echo 'Verifying Docker access...'",
          "if ! docker info > /dev/null 2>&1; then",
          "  echo ''",
          "  echo '⚠️  Cannot connect to Docker daemon'",
          "  echo ''",
          "  echo 'This usually means:'",
          "  echo '  1. Docker service is not running'",
          "  echo '     Fix: sudo systemctl start docker'",
          "  echo ''",
          "  echo '  2. Your user is not in docker group'",
          "  echo '     Fix: newgrp docker'",
          "  echo ''",
          "  echo '  3. You need to log out/back in'",
          "  echo '     Fix: Log out and log back in'",
          "  echo ''",
          "  exit 1",
          "fi",
          "echo '✓ Docker is running and accessible'",
          "echo ''"
        ]
      }
    },
    // Clone postiz-docker-compose repo
    {
      when: "{{!exists('app')}}",
      method: "shell.run",
      params: {
        message: [
          "echo 'Downloading Postiz...'",
          "git clone https://github.com/gitroomhq/postiz-docker-compose.git app"
        ]
      }
    },
    // Generate .env with secure random JWT secret
    {
      when: "{{!exists('app/.env')}}",
      method: "fs.write",
      params: {
        path: "app/.env",
        content: `# Auto-generated by Pinokio launcher
# Edit this file to configure social media integrations

MAIN_URL=http://localhost:4007
FRONTEND_URL=http://localhost:4007
NEXT_PUBLIC_BACKEND_URL=http://localhost:4007/api
JWT_SECRET=${JWT_SECRET}
DATABASE_URL=postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local
REDIS_URL=redis://postiz-redis:6379
BACKEND_INTERNAL_URL=http://localhost:3000
BACKEND_URL=http://localhost:3000
TEMPORAL_ADDRESS=temporal:7233
IS_GENERAL=true
DISABLE_REGISTRATION=false
RUN_CRON=true
STORAGE_PROVIDER=local
UPLOAD_DIRECTORY=/uploads
NEXT_PUBLIC_UPLOAD_DIRECTORY=/uploads

# === Social Media API Keys ===
X_API_KEY=
X_API_SECRET=
LINKEDIN_CLIENT_ID=
LINKEDIN_CLIENT_SECRET=
REDDIT_CLIENT_ID=
REDDIT_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
THREADS_APP_ID=
THREADS_APP_SECRET=
FACEBOOK_APP_ID=
FACEBOOK_APP_SECRET=
YOUTUBE_CLIENT_ID=
YOUTUBE_CLIENT_SECRET=
TIKTOK_CLIENT_ID=
TIKTOK_CLIENT_SECRET=
PINTEREST_CLIENT_ID=
PINTEREST_CLIENT_SECRET=
DRIBBBLE_CLIENT_ID=
DRIBBBLE_CLIENT_SECRET=
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
DISCORD_BOT_TOKEN_ID=
SLACK_ID=
SLACK_SECRET=
SLACK_SIGNING_SECRET=
MASTODON_URL=https://mastodon.social
MASTODON_CLIENT_ID=
MASTODON_CLIENT_SECRET=
BEEHIIVE_API_KEY=
BEEHIIVE_PUBLICATION_ID=
OPENAI_API_KEY=
EXTENSION_ID=icpokdlcikdmemjkeoojhocmhmehpaia
API_LIMIT=30
FEE_AMOUNT=0.05
NX_ADD_PLUGINS=false
`
      }
    },
    // Pull docker images
    {
      method: "shell.run",
      params: {
        path: "app",
        message: [
          "echo ''",
          "echo 'Downloading Docker images (this may take a few minutes)...'",
          "echo ''",
          "docker compose pull"
        ]
      }
    },
    // Success message
    {
      method: "shell.run",
      params: {
        message: [
          "echo ''",
          "echo '═══════════════════════════════════════════'",
          "echo '  ✅ Installation Complete!'",
          "echo '═══════════════════════════════════════════'",
          "echo ''",
          "echo 'Click Start to launch Postiz'",
          "echo ''",
          "echo 'First startup takes 1-2 minutes for all containers'",
          "echo 'to initialize.'",
          "echo ''",
          "echo 'Access Postiz at: http://localhost:4007'",
          "echo ''"
        ]
      }
    }
  ]
}
